# Generated by Django 4.2.4 on 2023-11-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
